### ISSUE TITLE
Неправильная связь студент-группа, в группе может быть много студентов

### ISSUE THREAD

**Issue by alexeychernykh** [Carapacik/TLPractice#1]
Сейчас при добавлении студентов создаются дубли названий групп.
Ссылки надо по другому поставить

https://github.com/Carapacik/TLPractice/blob/ed61e7341db07ebcf3f512a9c835187b2527c496/University/Group.cs#L7

**Comment by Carapacik** [comment]
Всё изменил

**Comment by Carapacik** [comment]
Проверено
