### ISSUE TITLE
Нельзя проверять ID по кол-ву строк в таблице

### ISSUE THREAD

**Issue by alexeychernykh** [Carapacik/TLPractice#2]
ID необязательно будет расти последовательно. Так же записи из БД могут удаляться.
Нужно проверять именно существование такого ID в БД

https://github.com/Carapacik/TLPractice/blob/ed61e7341db07ebcf3f512a9c835187b2527c496/University/Program.cs#L166

**Comment by Carapacik** [comment]
Всё изменил

**Comment by Carapacik** [comment]
Проверено
