### ISSUE TITLE
Замечания по Queries

### ISSUE THREAD

**Issue by alexeychernykh** [Carapacik/TLPractice#4]
1. Форматирование SQL запросов нужно так

```
                        INSERT INTO [dbo].[Student] (
                            [Name],
                            [Age])
                        VALUES (
                            @name,
                            @age)
                        SELECT SCOPE_IDENTITY()";
```

2. Вынести интерфейс класс, убрать статик методы. Создавать экземпляр объекта в Program.cs

https://github.com/Carapacik/TLPractice/blob/ed61e7341db07ebcf3f512a9c835187b2527c496/University/Queries.cs#L20

**Comment by Carapacik** [comment]
Всё изменил

**Comment by Carapacik** [comment]
Проверено
