### ISSUE TITLE
Использовать ID для JOIN

### ISSUE THREAD

**Issue by alexeychernykh** [Carapacik/TLPractice#5]
После исправления стуктуры таблиц JOIN должен делаться по ID
Название группы может поменяться, его не надо будет менять во всех остальных таблицах

https://github.com/Carapacik/TLPractice/blob/ed61e7341db07ebcf3f512a9c835187b2527c496/University/Queries.cs#L293

**Comment by Carapacik** [comment]
Всё изменил

**Comment by Carapacik** [comment]
Проверено
