### ISSUE TITLE
Неправильная связь Занятие-Группа

### ISSUE THREAD

**Issue by alexeychernykh** [Carapacik/TLPractice#6]
Тут нужна связь много-ко-многим через дополнительную сущность ЗанятиеДляГруппы
Запросы по подсчёту статистики тоже нужно будет поправить.

https://github.com/Carapacik/TLPractice/blob/ed61e7341db07ebcf3f512a9c835187b2527c496/University/Course.cs#L8

**Comment by Carapacik** [comment]
Добавил новую таблицу

**Comment by Carapacik** [comment]
Проверено
